[versions]

minSdk = "21"
compileSdk = "34"
targetSdk = "34"

kotlin = "1.8.22"
dependencyCheckPluginVersion = "0.47.0"
gradlePluginVersion = "8.1.0"
mavenPublishPluginVersion = "0.25.3"

composeViewModel = "2.6.1"
activityCompose = "1.7.2"

material = "1.9.0"
lifecycleRuntimeKtx = "2.6.1"

ksp = "1.8.22-1.0.11"

junit = "4.13.2"

compose = "1.5.0-beta03"
composeMaterial = "1.5.0-beta03"
composeCompiler = "1.4.8"
composeNavigation = "2.7.0-beta02"
accompanist = "0.31.5-beta"

ktxSerialization = "1.5.1"
mockk = "1.13.5"

compileTesting = "1.5.0"
composeWear = "1.1.2"

[plugins]
dependencyCheckPlugin = { id = "com.github.ben-manes.versions", version.ref = "dependencyCheckPluginVersion" }


[libraries]

# Plugins
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
pluginVersion = { module = "com.android.tools.build:gradle", version.ref = "gradlePluginVersion" }
mavenPublishPlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublishPluginVersion" }

# Android
androidMaterial = { module = "com.google.android.material:material", version.ref = "material" }

# AndroidX
androidx-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeViewModel" }

accompanist-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }

# Ksp
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# KtxSerialization
ktxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ktxSerialization" }

# Test
test-junit = { module = "junit:junit", version.ref = "junit" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-kotlinCompile = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "compileTesting" }
test-kotlinCompileKsp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "compileTesting" }

# Wear

wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "composeWear" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "composeWear" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "composeWear" }
wear-input = { module = "androidx.wear:wear-input", version = "1.1.0" }
