[versions]

minSdk = "21"
compileSdk = "33"
targetSdk = "33"

kotlin = "1.7.20"
dependencyCheckPluginVersion = "0.42.0"
gradlePluginVersion = "7.2.2"
mavenPublishPluginVersion = "0.18.0"

composeViewModel = "2.5.1"
activityCompose = "1.6.0"

material = "1.6.1"
lifecycleKtx = "2.5.1"
lifecycleRuntimeKtx = "2.5.1"

ksp = "1.7.20-1.0.6"

junit = "4.13.2"

compose = "1.3.0-rc01"
composeCompiler = "1.3.2"
composeNavigation = "2.5.2"
accompanist = "0.26.5-rc"

ktxSerialization = "1.4.0"
mockk = "1.13.2"


[plugins]
dependencyCheckPlugin = { id = "com.github.ben-manes.versions", version.ref = "dependencyCheckPluginVersion" }


[libraries]

# Plugins
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
pluginVersion = { module = "com.android.tools.build:gradle", version.ref = "gradlePluginVersion" }
mavenPublishPlugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublishPluginVersion" }

# Android
androidMaterial = { module = "com.google.android.material:material", version.ref = "material" }

# AndroidX
androidx-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeViewModel" }

accompanist-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }

# Ksp
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# KtxSerialization
ktxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ktxSerialization" }

# Test
test-junit = { module = "junit:junit", version.ref = "junit" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
